In [47]:
import requests
import pandas as pd

In [48]:
url = "https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100"

In [49]:
response = requests.get(url)
response.status_code

200

In [50]:
data = response.json()
type(data)

dict

In [51]:
data.keys()

dict_keys(['total_count', 'incomplete_results', 'items'])

In [52]:
len(data["items"])

100

In [53]:
df = pd.DataFrame(data["items"])

In [54]:
df.head()

,id,node_id,name,full_name,private,owner,html_url,description,fork,url,...,web_commit_signoff_required,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch,score
0,45717250,MDEwOlJlcG9zaXRvcnk0NTcxNzI1MA==,tensorflow,tensorflow/tensorflow,False,"{'login': 'tensorflow', 'id': 15658638, 'node_...",https://github.com/tensorflow/tensorflow,An Open Source Machine Learning Framework for ...,False,https://api.github.com/repos/tensorflow/tensor...,...,False,True,all,"[deep-learning, deep-neural-networks, distribu...",public,76082,2952,197212,master,1.0
1,155220641,MDEwOlJlcG9zaXRvcnkxNTUyMjA2NDE=,transformers,huggingface/transformers,False,"{'login': 'huggingface', 'id': 25720743, 'node...",https://github.com/huggingface/transformers,🤗 Transformers: the model-definition framework...,False,https://api.github.com/repos/huggingface/trans...,...,False,True,all,"[audio, deep-learning, deepseek, gemma, glm, h...",public,34305,2386,164297,main,1.0
2,343965132,MDEwOlJlcG9zaXRvcnkzNDM5NjUxMzI=,ML-For-Beginners,microsoft/ML-For-Beginners,False,"{'login': 'microsoft', 'id': 6154722, 'node_id...",https://github.com/microsoft/ML-For-Beginners,"12 weeks, 26 lessons, 52 quizzes, classic Mach...",False,https://api.github.com/repos/microsoft/ML-For-...,...,False,True,all,"[data-science, education, machine-learning, ma...",public,22017,14,89643,main,1.0
3,145553672,MDEwOlJlcG9zaXRvcnkxNDU1NTM2NzI=,funNLP,fighting41love/funNLP,False,"{'login': 'fighting41love', 'id': 11475294, 'n...",https://github.com/fighting41love/funNLP,中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽...,False,https://api.github.com/repos/fighting41love/fu...,...,False,True,all,[],public,15271,52,82578,master,1.0
4,21872392,MDEwOlJlcG9zaXRvcnkyMTg3MjM5Mg==,awesome-machine-learning,josephmisiti/awesome-machine-learning,False,"{'login': 'josephmisiti', 'id': 246302, 'node_...",https://github.com/josephmisiti/awesome-machin...,A curated list of awesome Machine Learning fra...,False,https://api.github.com/repos/josephmisiti/awes...,...,False,True,all,[],public,15617,26,74093,master,1.0

In [55]:
df.shape

(100, 82)

In [56]:
df.columns

Index(['id', 'node_id', 'name', 'full_name', 'private', 'owner', 'html_url',
       'description', 'fork', 'url', 'forks_url', 'keys_url',
       'collaborators_url', 'teams_url', 'hooks_url', 'issue_events_url',
       'events_url', 'assignees_url', 'branches_url', 'tags_url', 'blobs_url',
       'git_tags_url', 'git_refs_url', 'trees_url', 'statuses_url',
       'languages_url', 'stargazers_url', 'contributors_url',
       'subscribers_url', 'subscription_url', 'commits_url', 'git_commits_url',
       'comments_url', 'issue_comment_url', 'contents_url', 'compare_url',
       'merges_url', 'archive_url', 'downloads_url', 'issues_url', 'pulls_url',
       'milestones_url', 'notifications_url', 'labels_url', 'releases_url',
       'deployments_url', 'created_at', 'updated_at', 'pushed_at', 'git_url',
       'ssh_url', 'clone_url', 'svn_url', 'homepage', 'size',
       'stargazers_count', 'watchers_count', 'language', 'has_issues',
       'has_projects', 'has_downloads', 'has_wiki', 'has_pages',
       'has_discussions', 'forks_count', 'mirror_url', 'archived', 'disabled',
       'open_issues_count', 'license', 'allow_forking', 'is_template',
       'web_commit_signoff_required', 'has_pull_requests',
       'pull_request_creation_policy', 'topics', 'visibility', 'forks',
       'open_issues', 'watchers', 'default_branch', 'score'],
      dtype='object')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 82 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            100 non-null    int64
 1   node_id                       100 non-null    object
 2   name                          100 non-null    object
 3   full_name                     100 non-null    object
 4   private                       100 non-null    bool
 5   owner                         100 non-null    object
 6   html_url                      100 non-null    object
 7   description                   100 non-null    object
 8   fork                          100 non-null    bool
 9   url                           100 non-null    object
 10  forks_url                     100 non-null    object
 11  keys_url                      100 non-null    object
 12  collaborators_url             100 non-null    object
 13  teams_url                     100 non-null    object
 14  hooks_url                     100 non-null    object
 15  issue_events_url              100 non-null    object
 16  events_url                    100 non-null    object
 17  assignees_url                 100 non-null    object
 18  branches_url                  100 non-null    object
 19  tags_url                      100 non-null    object
 20  blobs_url                     100 non-null    object
 21  git_tags_url                  100 non-null    object
 22  git_refs_url                  100 non-null    object
 23  trees_url                     100 non-null    object
 24  statuses_url                  100 non-null    object
 25  languages_url                 100 non-null    object
 26  stargazers_url                100 non-null    object
 27  contributors_url              100 non-null    object
 28  subscribers_url               100 non-null    object
 29  subscription_url              100 non-null    object
 30  commits_url                   100 non-null    object
 31  git_commits_url               100 non-null    object
 32  comments_url                  100 non-null    object
 33  issue_comment_url             100 non-null    object
 34  contents_url                  100 non-null    object
 35  compare_url                   100 non-null    object
 36  merges_url                    100 non-null    object
 37  archive_url                   100 non-null    object
 38  downloads_url                 100 non-null    object
 39  issues_url                    100 non-null    object
 40  pulls_url                     100 non-null    object
 41  milestones_url                100 non-null    object
 42  notifications_url             100 non-null    object
 43  labels_url                    100 non-null    object
 44  releases_url                  100 non-null    object
 45  deployments_url               100 non-null    object
 46  created_at                    100 non-null    object
 47  updated_at                    100 non-null    object
 48  pushed_at                     100 non-null    object
 49  git_url                       100 non-null    object
 50  ssh_url                       100 non-null    object
 51  clone_url                     100 non-null    object
 52  svn_url                       100 non-null    object
 53  homepage                      92 non-null     object
 54  size                          100 non-null    int64
 55  stargazers_count              100 non-null    int64
 56  watchers_count                100 non-null    int64
 57  language                      77 non-null     object
 58  has_issues                    100 non-null    bool
 59  has_projects                  100 non-null    bool
 60  has_downloads                 100 non-null    bool
 61  has_wiki                      100 non-null    bool
 62  has_pages                     100 non-null    bool
 63  has_discussions               100 non-null    bool
 64  forks_count                   100 non-null    int64
 65  mirror_url                    0 non-null      object
 66  archived                      100 non-null    bool
 67  disabled                      100 non-null    bool
 68  open_issues_count             100 non-null    int64
 69  license                       78 non-null     object
 70  allow_forking                 100 non-null    bool
 71  is_template                   100 non-null    bool
 72  web_commit_signoff_required   100 non-null    bool
 73  has_pull_requests             100 non-null    bool
 74  pull_request_creation_policy  100 non-null    object
 75  topics                        100 non-null    object
 76  visibility                    100 non-null    object
 77  forks                         100 non-null    int64
 78  open_issues                   100 non-null    int64
 79  watchers                      100 non-null    int64
 80  default_branch                100 non-null    object
 81  score                         100 non-null    float64
dtypes: bool(14), float64(1), int64(9), object(58)
memory usage: 54.6+ KB

In [58]:
df.tail()

,id,node_id,name,full_name,private,owner,html_url,description,fork,url,...,web_commit_signoff_required,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch,score
95,126573668,MDEwOlJlcG9zaXRvcnkxMjY1NzM2Njg=,Machine-learning-learning-notes,Vay-keen/Machine-learning-learning-notes,False,"{'login': 'Vay-keen', 'id': 9793783, 'node_id'...",https://github.com/Vay-keen/Machine-learning-l...,周志华《机器学习》又称西瓜书是一本较为全面的书籍，书中详细介绍了机器学习领域不同类型的算法(...,False,https://api.github.com/repos/Vay-keen/Machine-...,...,False,True,all,[],public,1879,28,7761,master,1.0
96,290234921,MDEwOlJlcG9zaXRvcnkyOTAyMzQ5MjE=,awesome-youtubers,JoseDeFreitas/awesome-youtubers,False,"{'login': 'JoseDeFreitas', 'id': 37962411, 'no...",https://github.com/JoseDeFreitas/awesome-youtu...,An awesome list of awesome YouTubers that teac...,False,https://api.github.com/repos/JoseDeFreitas/awe...,...,False,True,all,"[awesome, awesome-list, list, youtube, youtubers]",public,496,2,7732,main,1.0
97,123568881,MDEwOlJlcG9zaXRvcnkxMjM1Njg4ODE=,Learn_Machine_Learning_in_3_Months,llSourcell/Learn_Machine_Learning_in_3_Months,False,"{'login': 'llSourcell', 'id': 1279609, 'node_i...",https://github.com/llSourcell/Learn_Machine_Le...,"This is the code for ""Learn Machine Learning i...",False,https://api.github.com/repos/llSourcell/Learn_...,...,False,True,all,[],public,2310,19,7604,master,1.0
98,17371412,MDEwOlJlcG9zaXRvcnkxNzM3MTQxMg==,h2o-3,h2oai/h2o-3,False,"{'login': 'h2oai', 'id': 1402695, 'node_id': '...",https://github.com/h2oai/h2o-3,"H2O is an Open Source, Distributed, Fast & Sca...",False,https://api.github.com/repos/h2oai/h2o-3,...,False,True,all,"[automl, big-data, data-science, deep-learning...",public,2026,2881,7495,master,1.0
99,184701688,MDEwOlJlcG9zaXRvcnkxODQ3MDE2ODg=,industry-machine-learning,firmai/industry-machine-learning,False,"{'login': 'firmai', 'id': 26666267, 'node_id':...",https://github.com/firmai/industry-machine-lea...,A curated list of applied machine learning and...,False,https://api.github.com/repos/firmai/industry-m...,...,False,True,all,"[data-science, datascience, example, firmai, j...",public,1249,3,7484,master,1.0

In [59]:
required_columns = [
    "name",
    "owner",
    "language",
    "stargazers_count",
    "forks_count",
    "watchers_count",
    "open_issues_count",
    "created_at",
    "updated_at",
    "license"
]

df = df[required_columns]

In [60]:
df.head()

,name,owner,language,stargazers_count,forks_count,watchers_count,open_issues_count,created_at,updated_at,license
0,tensorflow,"{'login': 'tensorflow', 'id': 15658638, 'node_...",C++,197212,76082,197212,2952,2015-11-07T01:19:20Z,2026-08-21T11:36:04Z,"{'key': 'apache-2.0', 'name': 'Apache License ..."
1,transformers,"{'login': 'huggingface', 'id': 25720743, 'node...",Python,164297,34305,164297,2386,2018-10-29T13:56:00Z,2026-08-21T11:36:26Z,"{'key': 'apache-2.0', 'name': 'Apache License ..."
2,ML-For-Beginners,"{'login': 'microsoft', 'id': 6154722, 'node_id...",Jupyter Notebook,89643,22017,89643,14,2021-03-03T01:34:05Z,2026-08-21T11:24:32Z,"{'key': 'mit', 'name': 'MIT License', 'spdx_id..."
3,funNLP,"{'login': 'fighting41love', 'id': 11475294, 'n...",Python,82578,15271,82578,52,2018-08-21T11:20:39Z,2026-08-21T09:14:39Z,None
4,awesome-machine-learning,"{'login': 'josephmisiti', 'id': 246302, 'node_...",Python,74093,15617,74093,26,2014-07-15T19:11:19Z,2026-08-21T11:29:01Z,"{'key': 'other', 'name': 'Other', 'spdx_id': '..."

In [61]:
df.shape

(100, 10)

In [62]:
df["owner"] = df["owner"].apply(lambda x: x["login"] if x else None)

In [63]:
df["owner"].head()

0        tensorflow
1       huggingface
2         microsoft
3    fighting41love
4      josephmisiti
Name: owner, dtype: object

In [64]:
df["license"] = df["license"].apply(lambda x: x["name"] if x else None)

In [65]:
df["license"].head()

0    Apache License 2.0
1    Apache License 2.0
2           MIT License
3                  None
4                 Other
Name: license, dtype: object

In [66]:
df.isnull().sum()

name                  0
owner                 0
language             23
stargazers_count      0
forks_count           0
watchers_count        0
open_issues_count     0
created_at            0
updated_at            0
license              22
dtype: int64

In [67]:
df["language"] = df["language"].fillna("Unknown")
df["license"] = df["license"].fillna("No License")

In [68]:
df.isnull().sum()

name                 0
owner                0
language             0
stargazers_count     0
forks_count          0
watchers_count       0
open_issues_count    0
created_at           0
updated_at           0
license              0
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
df = df.drop_duplicates()

In [71]:
df["created_at"] = pd.to_datetime(df["created_at"])
df["updated_at"] = pd.to_datetime(df["updated_at"])

In [72]:
df.dtypes

name                              object
owner                             object
language                          object
stargazers_count                   int64
forks_count                        int64
watchers_count                     int64
open_issues_count                  int64
created_at           datetime64[ns, UTC]
updated_at           datetime64[ns, UTC]
license                           object
dtype: object

In [73]:
df = df.rename(columns={
    "stargazers_count": "stars",
    "forks_count": "forks",
    "watchers_count": "watchers",
    "open_issues_count": "open_issues",
    "created_at": "created_date",
    "updated_at": "updated_date"
})

In [74]:
df.columns

Index(['name', 'owner', 'language', 'stars', 'forks', 'watchers',
       'open_issues', 'created_date', 'updated_date', 'license'],
      dtype='object')

In [75]:
df.head()

,name,owner,language,stars,forks,watchers,open_issues,created_date,updated_date,license
0,tensorflow,tensorflow,C++,197212,76082,197212,2952,2015-11-07 01:19:20+00:00,2026-08-21 11:36:04+00:00,Apache License 2.0
1,transformers,huggingface,Python,164297,34305,164297,2386,2018-10-29 13:56:00+00:00,2026-08-21 11:36:26+00:00,Apache License 2.0
2,ML-For-Beginners,microsoft,Jupyter Notebook,89643,22017,89643,14,2021-03-03 01:34:05+00:00,2026-08-21 11:24:32+00:00,MIT License
3,funNLP,fighting41love,Python,82578,15271,82578,52,2018-08-21 11:20:39+00:00,2026-08-21 09:14:39+00:00,No License
4,awesome-machine-learning,josephmisiti,Python,74093,15617,74093,26,2014-07-15 19:11:19+00:00,2026-08-21 11:29:01+00:00,Other

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          100 non-null    object
 1   owner         100 non-null    object
 2   language      100 non-null    object
 3   stars         100 non-null    int64
 4   forks         100 non-null    int64
 5   watchers      100 non-null    int64
 6   open_issues   100 non-null    int64
 7   created_date  100 non-null    datetime64[ns, UTC]
 8   updated_date  100 non-null    datetime64[ns, UTC]
 9   license       100 non-null    object
dtypes: datetime64[ns, UTC](2), int64(4), object(4)
memory usage: 7.9+ KB

In [77]:
df.isnull().sum()

name            0
owner           0
language        0
stars           0
forks           0
watchers        0
open_issues     0
created_date    0
updated_date    0
license         0
dtype: int64

In [78]:
df.duplicated().sum()

np.int64(0)

In [79]:
df.columns

Index(['name', 'owner', 'language', 'stars', 'forks', 'watchers',
       'open_issues', 'created_date', 'updated_date', 'license'],
      dtype='object')

In [80]:
df.shape

(100, 10)

In [81]:
df.to_csv("github_projects.csv", index=False)

In [82]:
df_check = pd.read_csv("github_projects.csv")

In [83]:
df_check.head()

,name,owner,language,stars,forks,watchers,open_issues,created_date,updated_date,license
0,tensorflow,tensorflow,C++,197212,76082,197212,2952,2015-11-07 01:19:20+00:00,2026-08-21 11:36:04+00:00,Apache License 2.0
1,transformers,huggingface,Python,164297,34305,164297,2386,2018-10-29 13:56:00+00:00,2026-08-21 11:36:26+00:00,Apache License 2.0
2,ML-For-Beginners,microsoft,Jupyter Notebook,89643,22017,89643,14,2021-03-03 01:34:05+00:00,2026-08-21 11:24:32+00:00,MIT License
3,funNLP,fighting41love,Python,82578,15271,82578,52,2018-08-21 11:20:39+00:00,2026-08-21 09:14:39+00:00,No License
4,awesome-machine-learning,josephmisiti,Python,74093,15617,74093,26,2014-07-15 19:11:19+00:00,2026-08-21 11:29:01+00:00,Other

In [84]:
df_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          100 non-null    object
 1   owner         100 non-null    object
 2   language      100 non-null    object
 3   stars         100 non-null    int64
 4   forks         100 non-null    int64
 5   watchers      100 non-null    int64
 6   open_issues   100 non-null    int64
 7   created_date  100 non-null    object
 8   updated_date  100 non-null    object
 9   license       100 non-null    object
dtypes: int64(4), object(6)
memory usage: 7.9+ KB

In [85]:
df_check.shape

(100, 10)

In [86]:
import os

os.path.exists("github_projects.csv")

True